[package]
name = "lumdareman"
version = "0.1.0"
authors = ["lapinot", "shhun"]
edition = "2018"

[dependencies]
sdl2-sys = "0.33"

[dependencies.sdl2]
version = "0.33"
features = ["image", "unsafe_textures"]
