from pygame.locals import *

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FRAME_RATE = 60
TILE = 32

CTRL_RIGHT = 0
CTRL_DOWN = 1
CTRL_LEFT = 2
CTRL_UP = 3
CTRL_BOMB = 4

CONTROLS = [K_RIGHT, K_DOWN, K_LEFT, K_UP, K_SPACE]
#CONTROLS = [K_e, K_o, K_a, K_COMMA, K_SPACE]

PLAYER_MAX_LIFE = 100
PLAYER_MAX_BOMBS = 5

PLAYER_SPEED = 6 * TILE / 1000
